apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-choosepath-org-tls
  namespace: choosepath
spec:
  secretName: prod-choosepath-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: choosepath.org
  dnsNames:
    - choosepath.org
