apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-develop
spec:
  acme:
    # The server URL for the ACME provider
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Your ACME account email address
    email: your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
