apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: choosepath
spec:
  acme:
    # The server URL for the ACME provider
    server: https://acme-v02.api.letsencrypt.org/directory
    # Your ACME account email address
    email: pavloskapoutsis@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik
