apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choosepath-ing
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.org/client-max-body-size: 50m
    nginx.org/use-gzip: true
    nginx.ingress.kubernetes.io/use-gzip: true
    nginx.ingress.kubernetes.io/gzip: "on"
    nginx.org/gzip: on
    nginx.org/gzip_types: "application/json text/css text/html text/javascript text/html application/vnd.ms-fontobject application/x-font-ttf font/opentype font/eot font/otf font/ttf font/woff2"
    nginx.ingress.kubernetes.io/gzip_types: "application/json text/css text/html text/javascript text/html application/vnd.ms-fontobject application/x-font-ttf font/opentype font/eot font/otf font/ttf font/woff2"
    nginx.org/gzip_min_length: 256
    nginx.ingress.kubernetes.io/gzip_min_length: 256
spec:
  rules:
    - host: choosepath.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  name: 80-tcp
          - path: /api/user-info
            pathType: Prefix
            backend:
              service:
                name: auth-service-service
                port:
                  name: 80-tcp
          - path: /login/oauth2
            pathType: Prefix
            backend:
              service:
                name: auth-service-service
                port:
                  name: 80-tcp
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: auth-service-service
                port:
                  name: 80-tcp
          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: auth-service-service
                port:
                  name: 80-tcp
  tls:
    - hosts:
        - choosepath.org
      secretName: prod-choosepath-org-tls
