apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: choosepath

resources:
  - ingress.yaml
  - clusterIssuer.yaml
  - cert.yaml
  - traefik-middleware.yaml

components:
  - common
  - ui
  - auth-service
  - db
