apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: choosepath
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: postgres-db-url
            - name: APP_BASE_URL
              value: "https://choosepath.org"
