apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: choosepath
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-image
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: db

