apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-service
    deployment: auth-service
  name: auth-service
  namespace: choosepath
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: auth-service
      deployment: auth-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: auth-service
        deployment: auth-service
    spec:
      containers:
        - env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: timezone
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: postgres-db-url
            - name: APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: auth-service-url
            - name: APP_SUCCESS_URL
              valueFrom:
                configMapKeyRef:
                  name: common-configmap
                  key: auth-service-url
          image: auth-service-image
          imagePullPolicy: Always
          name: auth-service
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 20
          #   timeoutSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: http
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 5
          #   timeoutSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
