apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
  namespace: choosepath-develop
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: auth-service
