apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: choosepath
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgis
          image: postgis/postgis
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "choosepathdb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - name: postgis-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgis-data
          persistentVolumeClaim:
            claimName: postgis-pvc
