apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-backup-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard # This should match the PVC's storage class
  hostPath:
    path: /mnt/data/postgres-backup # Path on the node (use a suitable directory)
