apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: choosepath-develop
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: db
