apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
data:
  timezone: Europe/Athens
  node-tls: "0"
  environment: "prod"

  # google maps
  google-maps-api-key: "AIzaSyCrFkoy3GLop2K12MeTHY0hwwvj8M_LToY"

  # ui
  ui-url: "https://choosepath.org"
  auth-return-url: "https://choosepath.org/login"

  # auth service
  auth-service-url: auth-service-service:8080

  # backend service
  backend-service-url: "https://choosepath.ddns.net"

  # postgres db
  postgres-db-url: db-service:5432/choosepathdb
