apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
data:
  environment: prod
  timezone: Europe/Athens

  # ui
  ui-url: "https://choosepath-develop.org"
  auth-return-url: "https://choosepath-develop.org/login"

  # auth service
  auth-service-url: auth-service-service:8080

  # backend service
  backend-service-url: "https://choosepath.ddns.net"

  # postgres db
  postgres-db-host: db-service.default.svc.cluster.local
  postgres-db: choosepathdb
