apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
data:
  timezone: Europe/Athens
  node-tls: "0"
  environment: "prod"

  # google maps
  google-maps-api-key: "AIzaSyCrFkoy3GLop2K12MeTHY0hwwvj8M_LToY"

  # auth api
  ui-url: "https://choosepath.org"
  backend-service-url: "https://choosepath.ddns.net/"

  # postgres db
  postgres-db-url: db-service:5432/choosepathdb
