apiVersion: v1
kind: ConfigMap
metadata:
  name: common-configmap
  namespace: choosepath-develop
data:
  environment: prod
  timezone: Europe/Athens

  # ui
  ui-url: "https://develop.choosepath.org"
  auth-return-url: "https://develop.choosepath.org/login"

  # auth service
  auth-service-url: auth-service-service:8080

  # backend service
  backend-service-url: "https://choosepath.ddns.net"

  # postgres db
  postgres-db-host: db-service.choosepath-develop.svc.cluster.local
  postgres-db: choosepathdb
