apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ui-image
    newName: cyberboy123/ui
    newTag: 1.1.38

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - spc.yaml
