apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ui-image
    newName: pavloskomple/test-frontend
    newTag: v2.0

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
