apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: ui-image
    newName: cyberboy123/ui-develop
    newTag: latest-20250217-122646

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - spc.yaml
