apiVersion: v1
kind: Service
metadata:
  name: ui-develop-service
  namespace: default
  labels:
    app: ui
spec:
  type: ClusterIP
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: ui
